General:
  # 谱面信息
  AudioFilePath: "user://path/to/audio"          # 音频文件路径
  AudioPreview: [1000, 3000]                     # 选曲界面歌曲预览开始-结束时间 (毫秒)
  Title: "TestSong"                              # 歌曲标题
  Artist: "TestArtist"                           # 艺术家
  Creator: "Creator"                             # 谱师
  DisplayDifficulty: 3                           # 显示难度 (整数)
  ChartDifficulty: 3.2                           # 谱面定数 (小数)
  BeatmapID: 291                                 # 谱面ID (十进制)
  BPM: 120                                       # 基准BPM
  EnableBPMsv: true                              # 是否基于BPM变速

Events:
  # 谱面事件，格式为: [类型, 起始时间, 参数]
  # 类型说明:
  #   1x - 中心轨道事件
  #   2x - 半球轨道事件
  #   3x - 背景事件
  #   00 - BPM修改

  - [11, 5000, [50,200]]                           # 示例：5000ms时中心轨道向右移动50px，时间200ms
  - [12, 5000, [30,200]]                           # 示例：5000ms时中心轨道逆时针旋转30度，时间200ms
  - [00, 15000, 140]                              # 示例：15000ms处将BPM修改为140

Notes:
  # 物件信息，格式为: [时间, 类型, 速度修正, 偏移位置, 参数]
  # 类型说明:
  #   1x - 中心轨道
  #   2x - 半球轨道
  #   1，2，3，4 分别为 Tap Hold Flick Slide
  #   参数只对 Hold和Flick 有效
  #   Hold 持续时间（ms）
  #   Flick 方向 （1，2，3 左上 中 右上）
  # 偏移位置对半球轨道有效（0-180度），中心轨道默认为-1
  # 时间单位为毫秒，表示Note应被击中的时间
  # 速度修正默认为1，先应用BPM修正再应用此项修正

  - [3000, 11, 1.0, -1, null]                 # 示例：3000ms处中心轨道默认速度Tap Note
  # - [4000, 21, 1.5, 90, null]                 # 示例：4000ms处半球轨道90度位置1.5倍速Tap Note
  - [6000, 12, 1.0, -1, 500]                  # 示例：6000ms处中心轨道Hold Note，持续500ms
  # - [6200, 13, 1.0, -1, 2]                    # 示例：6200ms处中心轨道Flick Note，向上
